<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AttributeValue extends Model
{
    public $table = 'attribute_values';

    protected $guarded = ['id'];

    public function attributes()
    {
        return $this->belongsTo('App\Models\Attribute', 'attribute_id');
    }
    public function products()
    {
        return $this->belongsToMany('App\Models\Product','product_value', 'attribute_value_id', 'product_id');
    }

    public function photos()
    {
        return $this->morphMany('App\Models\Photo','photoable');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($attValue){
            return false;
            $attValue->photos->delete();
        });
    }
}
